learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

learning_log/learning_logs/urls.py
"""Определяет схемы URL для Learning_logs"""

from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    
    #Домашняя страница
    path('', views.index, name='index'),
    
    #Страница со списклм всех тем
    path('topics/', views.topics, name='topics'),
    
    #Страница с подробной информацией по отдельной теме
    path('topic/<int:topic_id>/', views.topic, name='topic'),

    # Страница для добавления новой темы
    path('new_topic/', views.new_topic, name='new_topic'),
    
    # Страница для добавления новой записи
     path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),

    # Страница для редактирования записи
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),

    # Страница для удалния записей
    path('entry/<int:entry_id>/delete', views.delete_entry, name='delete_entry'),

    # Страница для удалния тем
    path('topic/<int:topic_id>/delete', views.delete_topic, name='delete_topic'),
    
]

learning_log/users/urls.py
"""Определяет схемы URL для пользователей"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Включить URL авторизации по умолчанию.
    path('', include('django.contrib.auth.urls')),

    # Страница регистрации.
    path('register/', views.register, name='register'),
]

learning_log/learning_logs/models.py
from django.db import models
from  django.contrib.auth.models import User


class Topic(models.Model):
    """Тема, которую изучает пользователь"""
    text = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        """Возвращает строковок представление модели"""
        return self.text
        
class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta: 
        verbose_name_plural = 'entries'
        
    def __str__(self):
        """Возвращение строковое представление модели."""
        return f"{self.text[:50]}..."

learning_log/users/models.py
from django.db import models

# Create your models here.

learning_log/learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}
        
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_log/learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

def index(request):
    """Домашняя страница приложения"""
    return render(request, 'learning_logs/index.html')

@login_required()
def topics(request):
    """Выводит список тем"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Выводит одну тему и все ее записи."""
    topic = Topic.objects.get(id=topic_id)
    # Проверка на принадлежность темы текущему пользователю
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required()
def new_topic(request):
    """Определяет новую тему."""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = TopicForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required()
def new_entry(request, topic_id):
    """Добавляет новую запись по конкретной теме."""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = EntryForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    # Вывести пустую или недействительную форму.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required()
def edit_entry(request, entry_id):
    """Редактирует существующую запись."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = EntryForm(instance=entry)
    else:
        # Отправка данных POST; обработать данные.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

@login_required()
def delete_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if request.method != 'POST':
        form = EntryForm()
    else:
        # Если подтверждение проходит
        entry.delete()
        return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic}
    return render(request, 'learning_logs/delete_entry.html', context)

@login_required()
def delete_topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        # Если подтверждение проходит
        topic.delete()
        return redirect('learning_logs:topics')

    context = {'topic': topic}
    return render(request, 'learning_logs/delete_topic.html', context)

learning_log/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        # Выводит пустую форму регистрации.
        form = UserCreationForm()
    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу.
            login(request, new_user)
            return redirect('learning_logs:index')

    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Журнал</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" href="{% static 'learning_logs/css/style.css' %}">

</head>

<body>
<div class="solid"></div>
<nav class="navbar navbar-expand-lg">
    <a class="navbar-brand" id="1222" href="{% url 'learning_logs:index'%}">Журнал обучения</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" id="1111" href="{% url 'learning_logs:topics'%}">Темы</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item, col">
                    <span class="navbar-text" >Привет, {{ user.username }} !</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link">|</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="11" href="{% url 'users:logout' %}">Выход</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %} ">Зарегистрироваться</a>
                </li>
                <li>
                    <a class="nav-link">/</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Aвторизироваться</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="square"></div>

<script>
    
    function rain(){
        let amount = 200
        let body = document.querySelector('body')
        let i = 0
        while (i < amount){
            let drop = document.createElement('i')
            let size = Math.random() * 5
            let posX = Math.floor(Math.random() * window.innerWidth)
            let delay = Math.random() * - 20
            let duration = Math.random() * 5

            drop.style.width = 0.2 + size + 'px'
            drop.style.left = posX + 'px'
            drop.style.animationDelay = delay + 's'
            drop.style.animationDuration =1 + duration + 's'
            body.appendChild(drop)
            i++
        }
    }

    rain();
</script>



<main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>

</main>

</body>

</html>

learning_log/learning_logs/templates/learning_logs/delete_entry.html
{% extends "learning_logs/base.html" %}
{% block page_header %}

    <style>
        .but { color: rgb(2, 255, 7)}
        .yellow { color: rgb(213, 162, 3)}
        .red { background: rgb(255, 0, 0)}
    </style>
    <div class="text-center">
        <h3 class="align-middle, yellow">Удалить запись?</h3>
    </div>

{% endblock page_header %}
{% block content %}

<form class="text-center " action="{% url 'learning_logs:delete_entry' entry.id %}" method='post'>
    {% csrf_token %}
    <a class="but" href="{% url 'learning_logs:topic' topic.id %}">Отменить</a>
    <button name='submit' id="22" class="btn btn-primary, red">Удалить</button>
</form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/delete_topic.html
{% extends "learning_logs/base.html" %}
{% block page_header %}

    <style>
        .but { color: rgb(2, 255, 7)}
        .yellow { color: rgb(213, 162, 3)}
        .red { background: rgb(255, 0, 0)}
    </style>

    <div class="text-center">
    <h3 class="align-middle, yellow">Удалить тему?</h3>
    </div>

{% endblock page_header %}
{% block content %}

    <form class="text-center " action="{% url 'learning_logs:delete_topic' topic.id %}" method='post'>
        {% csrf_token %}
        <a class="but" href="{% url 'learning_logs:topic' topic.id %}">Отменить</a>
        <button name='submit' id="333333" class="btn btn-primary, red">Удалить</button>
    </form>

 {% endblock content %}

learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% block page_header %}

    <style>
        .col { color: rgb(213, 162, 3) }
        .but { background: rgb(213, 162, 3); }
        .red { color: rgb(255, 0, 0)}
    </style>
    <h1 class="col">Изменить запись:</h1>

{% endblock page_header %}
{% block content %}

    <h1>
        <p><a class="col" href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    </h1>

    <h5>
    <a class="red" id="222" href="{% url 'learning_logs:delete_entry' entry.id %}">Удалить запись</a>
    </h5>
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
    <button name='submit' id="333" class="btn btn-primary, but">Сохранить изменения</button>
    </form>

 {% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block page_header %}

<style>
    .but { background: rgb(213, 162, 3); }
</style>

    <div class='jumbotron'>
        <h1 class="display-3">Отслеживайте свое обучение.</h1>
        <p class="lead">Создайте свой собственный журнал обучения и ведите список темы, которые вы изучаете. Всякий раз, когда вы узнаете что-то новое о теме, сделайте запись, резюмируя то, что вы узнали.</p>
        <a class="btn btn-lg btn-primary, but", id="1234" href="{% url 'users:register' %}" role="button">Зарегистрироваться &raquo;</a>
    </div>

{% endblock page_header %}

learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% block page_header %}

    <style>
        .col { color: rgb(213, 162, 3) }
        .but { background: rgb(213, 162, 3); }
        .red { color: rgb(255, 0, 0)}
    </style>
    <h1 class="col">Создать новую запись:</h1>

{% endblock page_header %}
{% block content %}

    <h1>
        <p><a class="col" href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    </h1>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit' id="2233" class="btn btn-primary, but">Создать запись</button>
    </form>

 {% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% block page_header %}

    <style>
        .col { color: rgb(213, 162, 3) }
        .but { background: rgb(213, 162, 3); }
        .red { color: rgb(255, 0, 0)}
    </style>
    <h1 class="col">Создать новую тему:</h1>

{% endblock page_header %}
{% block content %}

    <form action="{% url 'learning_logs:new_topic' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit" id="1123" class="btn btn-primary, but">Создать тему</button>
    </form>

 {% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}
{% block page_header %}

    <style>
        .but { color: rgb(213, 162, 3) }
        .col { color: rgb(188, 67, 252)}
    </style>
 <h3 class="but">{{ topic }}</h3>

{% endblock page_header %}
{% block content %}

<p>
    <a class="but" id="2333" href="{% url 'learning_logs:new_entry' topic.id %}">Создать новую запись</a>
</p>
<ul>
    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ entry.date_added|date:'M d, Y H:i' }}
                <small><a class="but" id="3333" href="{% url 'learning_logs:edit_entry' entry.id %}">Редактировать запись</a></small>
            </h4>
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p class="col">В этой теме пока нет записей.</p>
    {% endfor %}

</ul>
    <h5>
        <a class="red" id="33333" href="{% url 'learning_logs:delete_topic' topic.id %}">Удалить тему</a>
    </h5>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block page_header %}

    <style>
        .but { color: rgb(213, 162, 3)}
        .col { color: rgb(188, 67, 252)}
    </style>
    <h1 class="but">Темы:</h1>

{% endblock page_header %}
{% block content %}

<ul>
    {% for topic in topics %}
        <li><h3>
            <a href="{% url 'learning_logs:topic' topic.id %}" id="1223">{{ topic }}</a>
        </h3></li>
    {% empty %}
        <li><h3 class="col">Темы еще не добавлены.</h3></li>
    {% endfor %}
</ul>

 <h3>
     <a class="but" id="1122" href="{% url 'learning_logs:new_topic' %}">Создать новую тему:</a>
 </h3>


{% endblock content %}